name: fd-dev
channels:
- defaults
dependencies:
- python=3.9
- pip=22.1.2
- pip:
    - pandas==2.0.1
    - numpy==1.24.3
    - plotly==5.14.1
    - requests==2.31.0
    - sspipe==0.1.17
    - adata==1.2.0
    - akshare==1.11.94
